version = 1

test_patterns = ["test/**"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  module_system = "es-modules"
  environment = ["nodejs"]
